// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "suraj.more@quickheal.com"
        },
        "license": {
            "name": "Quick Heal",
            "url": "https://www.quickheal.com/useful-tools"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/emp": {
            "get": {
                "description": "Get details of all employees",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "all-employes"
                ],
                "summary": "Get details of all employees",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/daos.Employee"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create new employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "new-employee"
                ],
                "summary": "Create new employee",
                "parameters": [
                    {
                        "description": "Create Emplopyee",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/daos.EmployeeModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.response"
                        }
                    }
                }
            }
        },
        "/emp/{id}": {
            "put": {
                "description": "Update Empoyee by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "update-employee"
                ],
                "summary": "Update Empoyee by id",
                "parameters": [
                    {
                        "description": "Update Emplopyee",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/daos.EmployeeModel"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Emplopyee object id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Empoyee by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "delete-employee"
                ],
                "summary": "Delete Empoyee by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Emplopyee object id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.response"
                        }
                    }
                }
            }
        },
        "/emp/{name}": {
            "get": {
                "description": "Get details of one employee of name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employee-by-name"
                ],
                "summary": "Get details of one employee of name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Emplopyee name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/daos.Employee"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "daos.Employee": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "deptId": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                }
            }
        },
        "daos.EmployeeModel": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "deptId": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                }
            }
        },
        "utils.response": {
            "type": "object",
            "properties": {
                "data": {},
                "result": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "E.M.S. API's",
	Description:      "This is a simple crud opration for employee",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
